---
version: "2.0"

services:
  web:
    image: teeyeeyang/pytorch-docker-cpu:1.0
    env:
      - pubkey=your_public_ssh_key_here
    expose:
      - port: 22
        as: 22
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
        storage:
          size: 16Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        web:
          denom: uakt
          amount: 20

deployment:
  web:
    dcloud:
      profile: web
      count: 1